---
out: "./zkeys"

# Make sure that these paths are correct
circomPath: "~/.cargo/bin/circom"
snarkjsPath: "./node_modules/snarkjs/build/cli.cjs"
circomRuntimePath: "./node_modules/circom_runtime"
ffiasmPath: "./node_modules/ffiasm"

circomFlags: "--r1cs --sym --wasm --wat"

circuits:
  - template: "./circuits/verify_cabal.circom"
    component: "VerifyCabal"
    params: [64, 4, 10]
    pubInputs: ["merkleRoot", "nullifier"]
    type: "prod"
  - template: "./circuits/verify_sig_cabal.circom"
    component: "VerifySigCabal"
    params: [64, 4, 10]
    pubInputs: ["merkleRoot"]
    type: "prod"

ptauFiles:
  1:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_01.ptau"
    name: "powersOfTau28_hez_final_01.ptau"

  2:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_02.ptau"
    name: "powersOfTau28_hez_final_02.ptau"

  3:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_03.ptau"
    name: "powersOfTau28_hez_final_03.ptau"

  4:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_04.ptau"
    name: "powersOfTau28_hez_final_04.ptau"

  5:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_05.ptau"
    name: "powersOfTau28_hez_final_05.ptau"

  6:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_06.ptau"
    name: "powersOfTau28_hez_final_06.ptau"

  7:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_07.ptau"
    name: "powersOfTau28_hez_final_7.ptau"

  8:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_08.ptau"
    name: "powersOfTau28_hez_final_8.ptau"

  9:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_09.ptau"
    name: "powersOfTau28_hez_final_9.ptau"

  10:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_10.ptau"
    name: "powersOfTau28_hez_final_10.ptau"

  11:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_11.ptau"
    name: "powersOfTau28_hez_final_11.ptau"

  12:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_12.ptau"
    name: "powersOfTau28_hez_final_12.ptau"

  13:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_13.ptau"
    name: "powersOfTau28_hez_final_13.ptau"

  14:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_14.ptau"
    name: "powersOfTau28_hez_final_14.ptau"

  15:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_15.ptau"
    name: "powersOfTau28_hez_final_15.ptau"

  16:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_16.ptau"
    name: "powersOfTau28_hez_final_16.ptau"

  17:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_17.ptau"
    name: "powersOfTau28_hez_final_17.ptau"

  18:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_18.ptau"
    name: "powersOfTau28_hez_final_18.ptau"

  19:
    url: "https://hermezptau.blob.core.windows.net/ptau/powersOfTau28_hez_final_19.ptau"
    name: "powersOfTau28_hez_final_19.ptau"
